// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsGCEa1Z4uOvasLxxOBR5uATKKXE1J2co',
    appId: '1:92514860692:web:40bb2716d75777d7a9fe81',
    messagingSenderId: '92514860692',
    projectId: 'ostad-7c47a',
    authDomain: 'ostad-7c47a.firebaseapp.com',
    storageBucket: 'ostad-7c47a.appspot.com',
    measurementId: 'G-953MZE7M41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xK7IuH8wLgsgz9SF9X2qXv66pSFjtf4',
    appId: '1:92514860692:android:0a32dc9c387fba4ca9fe81',
    messagingSenderId: '92514860692',
    projectId: 'ostad-7c47a',
    storageBucket: 'ostad-7c47a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAplDHSiY1RE4n1v1JNyKwqpWfkUjObmyA',
    appId: '1:92514860692:ios:45342fe53f3b3e4aa9fe81',
    messagingSenderId: '92514860692',
    projectId: 'ostad-7c47a',
    storageBucket: 'ostad-7c47a.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAplDHSiY1RE4n1v1JNyKwqpWfkUjObmyA',
    appId: '1:92514860692:ios:4302039140ce04fda9fe81',
    messagingSenderId: '92514860692',
    projectId: 'ostad-7c47a',
    storageBucket: 'ostad-7c47a.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
